web/src/IOasis/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.contrib.auth import views
from django.urls.conf import include
from IOasis.views import index
from django.conf.urls import include
from user.views import login, logout, register

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    re_path(r'^$|^index/$', index, name='index'),
    path('user/', include('user.urls', namespace='user')),
]

web/src/scist_scoreboard/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.contrib.auth import views
from scist_scoreboard.views import index, login, logout, register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', login, name='login'),
    path('accounts/logout/', logout, name='logout'),
    path('accounts/register/', register, name='register'),
    re_path(r'^$|^index/$', index),
]

web/src/user/urls.py
from django.urls import path
from user.views import UserEditPage

app_name = 'user'

urlpatterns = [
    path('<user_id>/edit/', UserEditPage, name='edit'),
]

web/src/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title> {% block title%}{% endblock%} </title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        {% block head %}{% endblock %}
    </head>
    <body>
        {% load static %}
        <!-- .navbar-expand-{sm|md|lg|xl}決定在哪個斷點以上就出現漢堡式選單 -->
        <!-- navbar-dark 文字顏色 .bg-dark 背景顏色 -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <!-- .navbar-brand 左上LOGO位置 -->
            <a class="navbar-brand" href="/">
                <img src="{% static 'img/IOasis.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="">
                <span class="h3 mx-1">IOasis</span>
            </a>
            <!-- .navbar-toggler 漢堡式選單按鈕 -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <!-- .navbar-toggler-icon 漢堡式選單Icon -->
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- .collapse.navbar-collapse 用於外層中斷點群組和隱藏導覽列內容 -->
            <!-- 選單項目&漢堡式折疊選單 -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                <!-- active表示當前頁面 -->
                <li class="nav-item active">
                    <a class="nav-link" href="/"> 首頁 <span class="sr-only">(current)</span></a>
                </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'user:edit' user_id=user.id %}" style="color: white"> {{ user.username }} <span class="sr-only">(current)</span></a>
                        <a class="nav-link" href="{% url 'logout' %}" style="color: white"> 登出 <span class="sr-only">(current)</span></a>
                    {% else %}
                        <a class="nav-link" href="{% url 'login' %}" style="color: white"> 登入 <span class="sr-only">(current)</span></a>
                        <a class="nav-link" href="{% url 'register' %}" style="color: white"> 註冊 <span class="sr-only">(current)</span></a>
                    {% endif %}
                </button>
                </form>
            </div>
        </nav>
        <br>
        {% block body %}{% endblock %}
    </body>
</html>

web/src/templates/index.html
{% extends 'base.html' %}
{% block title %} 首頁 {% endblock%}
{% block body %}
    <div class="container">
        <h1>Index</h1>
        <a href="/admin/"> Admin Page </a>
        <br>
        <a href={% url 'register' %}> Register </a>
        <br>
        <a href={% url 'login' %}> login </a>
        <br>
        <a href={% url 'logout' %}> logout </a>
    </div>
{% endblock %}